[theme]
base="dark"
backgroundColor="#060809"
secondaryBackgroundColor="#0D131D"
textColor="#cad6f2"
primaryColor="#72a1de"

[theme.sidebar]
backgroundColor="#0A0E15"
secondaryBackgroundColor="#111827"
textColor="#cad6f2"
primaryColor="#72a1de"
